デザイン修正()          2022/08/02
tmcoco0228si/deegle-translate-view pull request #11
Opened 2022-08-02 13:25 UTC by tmcoco0228si

## 変更の概要

* 変更の概要
* 関連するIssueやプルリクエスト

## なぜこの変更をするのか

* 変更をする理由
* 前提知識がなくても分かるようにする

## やったこと

* [x] やったこと
* [ ] やっていること

## 変更内容

* UIの変更ならスクリーンショット
* APIの変更ならリクエストとレスポンス

## 影響範囲

* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること

## どうやるのか

* 使い方
* 再現手順

## 課題

* 悩んでいること
* とくにレビューしてほしいところ

## 備考

* その他に伝えたいこと

2022-08-06 04:14 UTC, y-magavel requested changes
プルリクありがとうございます。
ローカルで画面を確認しました。良い感じだと思います。
（画面のスクリーンショットなんかもあるとさらに良いと思います）

細かい部分ですが、気になった箇所がいくつかあるのでコメントつけています。
ご確認のほどお願いいたします。

2022-08-06 04:14 UTC, y-magavel commented on src/pages/components/Footer.tsx
> +export default  Footer;
スペースが二つ入ってしまっているみたいです。

2022-08-06 04:14 UTC, y-magavel commented on src/pages/components/Header.tsx
> +  <header className="bg-blue-600  text-white p-4">
returnと中身のインデントが同じになってしまっているようです。

2022-08-06 04:14 UTC, y-magavel commented on src/pages/components/LanguageSwichingTab.tsx
> +  <div className="flex justify-center">
ulタグとdivタグのインデントが同じになっているようです。

2022-08-06 04:14 UTC, y-magavel commented on src/pages/components/LanguageSwichingTab.tsx
> +</ul>
ulの閉じタグのインデントがずれてしまっているようです。

2022-08-06 04:14 UTC, y-magavel commented on src/pages/components/LanguageSwichingTab.tsx
> +    <a href="#" className="inline-block py-3 px-4 text-white bg-blue-600 rounded-lg active" aria-current="page">Japanese</a>
liタグとaタグのインデントが同じになっているようです。

2022-08-06 04:14 UTC, y-magavel commented on src/pages/components/UserTranslationText.tsx
> +            <div className="sm:flex justify-center ms:px-24">
インデントに過剰なスペースが含まれているようです。

2022-08-06 04:14 UTC, y-magavel commented on src/pages/index.tsx
> +import { FontAwesomeIcon } from "@fortawesome/react-fontawesome" ;
末尾のセミコロンの前に不要なスペースがあるようです。

2022-08-06 04:14 UTC, y-magavel commented on src/pages/index.tsx
> +  const goodDeeple = () => {
関数名がgoodDeepleになっていますが、goodDeeplのタイポではないでしょうか？

2022-08-06 09:04 UTC, tmcoco0228si commented
お疲れ様です。
修正依頼の件、ご対応致しました。
お手隙の際に、ご確認いただければ幸いです。

2022-08-07 05:55 UTC, y-magavel requested changes

2022-08-07 05:55 UTC, y-magavel commented on src/pages/components/UserTranslationText.tsx
> +            <div className="sm:flex justify-center ms:px-24">
@tmcoco0228si 

> インデントに過剰なスペースが含まれているようです。

こちら再確認をお願いします。

2022-08-07 06:18 UTC, y-magavel approved these changes
ご対応ありがとうございました。

2022-08-07 06:19 UTC, merged